### ISSUE TITLE
Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist

### ISSUE THREAD

**Issue by dingziran** [Tjatse/pm2-gui#26]
pm2-gui  0.1.1
pm2 0.14.5
ubuntu 14

**Comment by Tjatse** [comment]
@dingziran Seems that your `pm2-gui` instance can not locate the PM2 root, you can manually setting it by `vi` the `pm2-gui.ini` file (it's under `~/.pm2/pm2-gui.ini` directory by default, otherwise you can use `sudo find  / -name pm2-gui.ini` to find it).

[pm2 root config](https://github.com/Tjatse/pm2-gui#cli_confs)

**Comment by dingziran** [comment]
I think the problem is pm2 doesn't contain conf.js and pm2-gui doesn't load a default conf.js? I copy a conf.js from pm2-gui demo and it works.

**Comment by Tjatse** [comment]
Yap, that could be a problem, `pm2-gui` depends on `PM2`.
Feel free to reopen this al file a new one if you still get problems with `pm2-gui`. :)

**Comment by jiangtao** [comment]
pm2 root config没有了 配置上去也不管用，在centos上
