### ISSUE TITLE
Error: xhr poll error

### ISSUE THREAD

**Issue by Daaru00** [Tjatse/pm2-gui#32]
Hi,
I receiving an error in web interface `Can not connect to the server due to Error: xhr poll error`. 
I currently serving web interface with nginx in https protocol but in console I see the connection on http protocol.
In the config file I set `origins = https://MYHOST:8088` but the issue persist.

what is the problem?

**Comment by Tjatse** [comment]
It seems a network issue with `socket.io`
Are you serving web with a public IP but access the `pm2-gui` agents via private IP, e.g.:
We Interface:
```
https://my.domain.com
```
> Using Nginx as Reverse proxy server, and the public IP of `my.domain.com` is `100.123.4.1` (fake of course, for example)

In the `pm2-gui.ini` all the addresses of `remotes` should be public IPs too, it can not works with private/locally IPs

Otherwise:
[Serving apps locally with nginx and custom domain](https://github.com/Tjatse/pm2-gui#serving-apps-locally-with-nginx-and-custom-domain)

**Comment by mekwall** [comment]
Having the same issue. pm2-gui is trying to connect to socket.io on the port which the node server (port 3000) is running on, and not the port that is used by nginx (port 80).

**Comment by samio80** [comment]
Having the same problem any update on this??

**Comment by Tjatse** [comment]
Try `pm2-gui@0.1.4` and [here](examples/pm2.example.com.conf) is an example of nginx conf

**Comment by ohoroyoi** [comment]
same here.

**Comment by dmatora** [comment]
same issue
half of requests are successful, half - are not
<img width="815" alt="image" src="https://github.com/Tjatse/pm2-gui/assets/647062/40b40fd4-0857-46ee-b06f-4194ef9c8144">
